shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver

overrides:
  h3: ^1.15.11
  vite: ^8.0.8
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@iconify-json/carbon': ^1.2.21
  '@iconify-json/heroicons': ^1.2.3
  '@iconify-json/logos': ^1.2.11
  '@iconify-json/material-symbols': ^1.2.71
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/radix-icons': ^1.2.6
  '@iconify-json/simple-icons': ^1.2.82
  '@iconify-json/uil': ^1.2.3
  '@iconify-json/unjs': ^1.2.3
  '@iconify-json/vscode-icons': ^1.2.49
  '@inspira-ui/plugins': ^0.0.2
  '@nuxt/content': ^3.13.0
  '@nuxt/devtools': 3.2.4
  '@nuxt/fonts': ^0.14.0
  '@nuxt/image': ^2.0.0
  '@nuxt/scripts': 1.0.0-rc.7
  '@nuxt/ui': ^4.7.1
  '@nuxtjs/mcp-toolkit': 0.11.0
  '@nuxtjs/seo': ^5.1.3
  '@sentry/nuxt': ^10.52.0
  '@unovis/vue': ^1.6.5
  '@vueuse/core': ^14.3.0
  '@vueuse/nuxt': ^14.3.0
  agents: ^0.12.3
  better-sqlite3: ^12.10.0
  case-police: ^2.2.1
  clsx: ^2.1.1
  consola: ^3.4.2
  date-fns: ^4.1.0
  drizzle-orm: ^0.45.2
  eslint: ^10.3.0
  eslint-plugin-harlanzw: ^0.13.0
  lint-staged: ^17.0.4
  markdownlint-cli: ^0.48.0
  motion-v: ^2.2.1
  nitro-cloudflare-dev: ^0.2.2
  nuxt: ^4.4.5
  nuxt-ai-ready: ^1.3.2
  nuxt-auth-utils: ^0.5.29
  nuxt-build-cache: ^0.1.1
  nuxt-lodash: ^2.5.3
  nuxt-og-image: ^6.5.0
  nuxt-skew-protection: ^1.1.1
  octokit: ^5.0.5
  ofetch: ^1.5.1
  shiki: ^4.0.2
  shiki-transformer-color-highlight: ^1.1.0
  simple-git-hooks: ^2.13.1
  sponsorkit: ^17.1.0
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.0
  tailwindcss-animate: ^1.0.7
  three: ^0.184.0
  troisjs: ^0.3.4
  wrangler: ^4.90.1
  zod: ^4.4.3

ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - sharp
  - simple-git-hooks
  - vue-demi
  - workerd

trustPolicyIgnoreAfter: 262800
