export const CLOUDFLARE_REQUIRED_SECRETS = [
  'NUXT_CLOUDFLARE_ANALYTICS_API_TOKEN',
  'NUXT_EMAIL_OCTOPUS_TOKEN',
  'NUXT_GITHUB_ACCESS_TOKEN',
  'NUXT_GITHUB_AUTH_CLIENT_SECRET',
  'NUXT_GITHUB_AUTH_TOKEN',
  'NUXT_GITHUB_SPONSORS_TOKEN',
  'NUXT_GOOGLE_API_TOKEN',
  'NUXT_OAUTH_GITHUB_CLIENT_SECRET',
  'NUXT_SESSION_PASSWORD',
]
